### ISSUE TITLE
Unleash does not work with node 8

### ISSUE THREAD

**Issue by nicojs** [Netflix/unleash#4]
Hi, i decided i would try out this unleash thing. When i tried to do a dry run it didn't work:

```bash
$ npm run release -- -d

> install-local@0.3.1 release C:\z\github\nicojs\node-install-local
> unleash "-d"

C:\z\github\nicojs\node-install-local\node_modules\require-dir\index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
```

This seems to be a problem with `require-dir` as stated here: https://github.com/tjunnone/npm-check-updates/issues/363#issuecomment-308452577. Maybe we need to update that package?

**Comment by jameswomack** [comment]
@nicojs thank you so much for calling this to my attention. I wish I'd seen your issue earlier.

I've not used Node 8 for anything yet & Unleash hasn't been published/run through CI since the 8 release, so as far as I knew Unleash was working great (with Node 7.7.3 and earlier). Anyone is welcome to open a pull request to solve this today. I'll approve a fix. If that doesn't happen, I will look into it myself sometime over the next 48 hours.

**Comment by jameswomack** [comment]
@nicojs `+ unleash@1.6.0` solves this issue via an upgrade to `gulp-git@2.3.2`. 

[Here's](https://github.com/stevelacy/gulp-git/releases/tag/gulp-git%402.3.2) the gulp-git release withe the fix.

The Unleash release fixing this is [here](https://github.com/Netflix/unleash/releases/tag/v1.6.0).
